/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'My' at '05.11.15 15:43' with Gradle 2.7
 *
 * @author My, @date 05.11.15 15:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
