import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'My' at '05.11.15 15:43' with Gradle 2.7
 *
 * @author My, @date 05.11.15 15:43
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
		//assertFalse("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
